import os

ENV_NAME = os.environ['ENV_NAME']
AWS_REGION = os.environ['AWS_REGION']

AWS_DYNAMODB_ENDPOINT_URL = os.getenv('AWS_DYNAMODB_ENDPOINT_URL', None)
DYNAMODB_MASTER_TABLE_NAME = os.environ['DYNAMODB_MASTER_TABLE_NAME']
DYNAMODB_TRANSACTION_TABLE_NAME = os.environ['DYNAMODB_TRANSACTION_TABLE_NAME']

AWS_S3_BUCKET_NAME = os.getenv('AWS_S3_BUCKET_NAME')

ALLOW_ORIGINS = os.environ['ALLOW_ORIGINS'].split(',')
ALLOW_CREDENTIALS = os.environ['ALLOW_CREDENTIALS'].lower() == 'true'
ALLOW_METHODS = os.environ['ALLOW_METHODS'].split(',')
ALLOW_HEADERS = os.environ['ALLOW_HEADERS'].split(',')

COGNITO_USER_POOL_ID = os.environ['COGNITO_USER_POOL_ID']
COGNITO_USER_POOL_CLIENT_ID = os.environ['COGNITO_USER_POOL_CLIENT_ID']